name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          fetch-depth: 0

      - name: Cache yarn dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Setup Sentry CLI
        uses: mathrix-education/setup-sentry-cli@0.1.0
        with:
          token: ${{ SECRETS.SENTRY_TOKEN }}
          organization: syzible-com
          project: drynk-api

      - name: Install dependencies
        run: yarn install

      - name: Lint code for errors
        run: yarn lint:code

      - name: Lint package.json dependency versions
        run: yarn lint:dependencies:check

      - name: Run tests
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          yml: codecov.yml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create new Sentry release
        run: sentry-cli releases new $(sentry-cli releases propose-version)

      - name: Build project
        run: yarn build

      - name: Upload sourcemaps to Sentry
        run: sentry-cli releases files $(sentry-cli releases propose-version) upload-sourcemaps ./dist

      - name: Associate release commits
        run: sentry-cli releases set-commits --auto $(sentry-cli releases propose-version)

      - name: Finalise Sentry release
        run: sentry-cli releases finalize $(sentry-cli releases propose-version)

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Dokku
        uses: thadeu/easily-dokku-action@v1.0.8
        env:
          PROJECT: drynk-api
          FLAGS: -f
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_HOST: syzible.com
